#ifndef __ObserverGUIMyFrame_generated__
#define __ObserverGUIMyFrame_generated__

/**
@file
Subclass of MyFrame_generated, which is generated by wxFormBuilder.
*/

#include "MyFrame_generated.h"

//// end generated include

/** Implementing MyFrame_generated */
class ObserverGUIMyFrame_generated : public MyFrame_generated
{
	protected:
		// Handlers for MyFrame_generated events.
		void onStartButtonClicked( wxCommandEvent& event );
		void onAddPriceObserverClicked( wxCommandEvent& event );
		void onAddHighObserverClicked( wxCommandEvent& event );
		void onAddLowObserverClicked( wxCommandEvent& event );
		void onAddAverageObserverClicked( wxCommandEvent& event );
	public:
		/** Constructor */
		ObserverGUIMyFrame_generated( wxWindow* parent );
	//// end generated class members
	
};

#endif // __ObserverGUIMyFrame_generated__
